In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2871, 5143, 2986, 6537],
 [2871, 5143, 2986, 8941],
 [2871, 2949, 2986, 587],
 [1086, 5347, 3372, 1545, 3666],
 [1086, 5347, 3372, 1545, 374],
 [8805, 2871, 4489, 2986, 3870],
 [2037, 3974, 9357, 1545]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2871 5143 2986 6537]
 [   0    0    0    0 2871 5143 2986 8941]
 [   0    0    0    0 2871 2949 2986  587]
 [   0    0    0 1086 5347 3372 1545 3666]
 [   0    0    0 1086 5347 3372 1545  374]
 [   0    0    0 8805 2871 4489 2986 3870]
 [   0    0    0    0 2037 3974 9357 1545]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 259ms/step


array([[[ 4.51683998e-04,  4.14721034e-02,  2.84641050e-02,
          3.23225148e-02, -3.00734397e-02,  2.07559206e-02,
          2.08613388e-02,  2.99853794e-02, -4.68786731e-02,
          2.50031464e-02],
        [ 4.51683998e-04,  4.14721034e-02,  2.84641050e-02,
          3.23225148e-02, -3.00734397e-02,  2.07559206e-02,
          2.08613388e-02,  2.99853794e-02, -4.68786731e-02,
          2.50031464e-02],
        [ 4.51683998e-04,  4.14721034e-02,  2.84641050e-02,
          3.23225148e-02, -3.00734397e-02,  2.07559206e-02,
          2.08613388e-02,  2.99853794e-02, -4.68786731e-02,
          2.50031464e-02],
        [ 4.51683998e-04,  4.14721034e-02,  2.84641050e-02,
          3.23225148e-02, -3.00734397e-02,  2.07559206e-02,
          2.08613388e-02,  2.99853794e-02, -4.68786731e-02,
          2.50031464e-02],
        [ 3.22377570e-02, -2.21506357e-02, -1.17762312e-02,
         -4.28673886e-02, -7.98217952e-05,  5.19717857e-03,
         -2.37097871e-02,  6.35801628e-03,  1.598836